# Generated by Django 3.2.5 on 2021-08-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_explore_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='play',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
