# Generated by Django 3.2.5 on 2021-08-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explore',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
